using System;
class Program
{
    // recursive method printRow prints n characters of # on one line
    static void printRow(int n)
    {
        if (n < 1)
            return;
        Console.Write("#");
        printRow(n - 1);
    }
    // recursive method printPattern prints n rows of string pattern generated by recursive method printRow
    static void printPattern(int n)
    {
        if (n < 1)
            return;
        printRow(n);
        Console.WriteLine();
        printPattern(n - 1);
    }
    public static void Main()
    {
        printPattern(5);
    }
}
